# Image Input/Output
# ----------------------------------------------------------------------------------------------
in_channels: 3
num_classes: 2
height: 400 #for PHR-CB experiment patch size = height = width
width: 400

# Training
# ----------------------------------------------------------------------------------------------
# mnet = fapnet, unet, ex_mnet*, dncnn, u2net, vnet, unet++, sm_unet, sm_linknet, sm_fpn, sm_pspnet*, kuc_vnet, kuc_unet3pp, kuc_r2unet,# kuc_unetpp*, kuc_restunet, kuc_tensnet*, kuc_swinnet, kuc_u2net,| kuc_attunet, ad_unet, transformer
model_name: fapnet
batch_size: 32   #64
epochs: 500
learning_rate: !!float 3e-4
val_plot_epoch: 10
augment: False
transfer_lr: False
gpu: !!str 3
trainOn: all  # ignore it

# Experiment Setup
# ----------------------------------------------------------------------------------------------
# regular/cls_balance/patchify/patchify_WOC
# cfr = regular, cfr_cb = cls_balance, phr = patchify, phr_cb = patchify_WOC
experiment: test_per

# Patchify (phr & phr_cb experiment)
# ----------------------------------------------------------------------------------------------
patchify: True
patch_class_balance: True # whether to use class balance while doing patchify
patch_size: 256 # height = width, anyone is suitable
stride: 64
p_train_dir: json/train_patch_phr_cb_256.json
p_valid_dir: json/valid_patch_phr_cb_256.json
p_test_dir: json/test_patch_phr_cb_256.json
p_eval_dir: json/eval_patch_phr_cb_256.json
# Dataset
# --------------------------------mask--------------------------------------------------------------
weights: False # False if cfr, True if cfr_cb
balance_weights: [1.8, 8.2]
dataset_dir: /home/mdsamiul/github_project/road_segmentation/data/
root_dir: /home/mdsamiul/github_project/road_segmentation/
train_size: 0.8
train_dir: train.csv
valid_dir: valid.csv
test_dir: test.csv
eval_dir: eval.csv
# Logger/Callbacks
# ----------------------------------------------------------------------------------------------
csv: True
val_pred_plot: True
lr: True
tensorboard: True
early_stop: False
checkpoint: True
patience: 300 # required for early_stopping, if accuracy does not change for 500 epochs, model will stop automatically

# Evaluation
# ----------------------------------------------------------------------------------------------
#load_model_name : m.hdf5
load_model_name: fapnet_ex_phr_cb_32_1000_ep_1000_02-Dec-22.hdf5
load_model_dir: None
evaluation: True
video_path: None    #/home/mdsamiul/github_project/road_segmentation/data/video.mp4
# Prediction Plot
# ----------------------------------------------------------------------------------------------
plot_single: False # if True, then only index x_test image will plot
index: -1 #170 # by default -1 means random image else specific index image provide by user
